### PR TITLE
Update Go to 1.19, add support for pagination in GetList methods and some fix.

### PR DESCRIPTION
**Pull request by gin-melodic**
Because of the use of generics in the automatic paging method, an updated go version is required.

- Support for pagination in GetList methods.
- For the new version of openproject, update the attachment struct.
- Fill out the work package structure.
- Fix an issue in the filter that causes it to lose the comma when there are multiple options.
- Update the json file for all unit tests.

### CODE REVIEW

**Comment by gin-melodic** [comment]
I can't confirm what is causing the CI to fail, the local tests are successful.

**Comment by manuelbcd** [comment]
Hi @gin-melodic, thank you very much for your contribution, let me have a go and try to find out what is the issue with the tests

**Comment by manuelbcd** [comment]
The code commits look good to me but I can't access to the security report because it is outdated. Do you mind to send a new commit to the PR (text minor change) so that it can be re-generated?

Thank you @gin-melodic

**Comment by gin-melodic** [comment]
OK. I will send a new PR.

By the way, I used the "make all" command and discovered various race and static check issues. They are all fixed by the fresh commits in PR.

**Pull request closed without merging**
